checkpoints:
  checkpoint_interval: 1000
  checkpoints_path: /fsx/phuc/new_workspace/experiments/fp8_for_nanotron/exp701aab10_100m_bfloat16_baseline_like_exp602ae3_with_adam_eps_1.0e-8_and_bs_320_and_smol_dataset_but_wd_0.8/checkpoints
  checkpoints_path_is_shared_file_system: false
  save_initial_state: false


# data_stages:
# - data:
#     dataset:
#       dataset_overwrite_cache: false
#       dataset_processing_num_proc_per_process: 1
#       hf_dataset_config_name: null
#       hf_dataset_or_datasets: roneneldan/TinyStories
#       hf_dataset_splits: train
#       text_column_name: text
#     num_loading_workers: 1
#     seed: 42
#   name: Stable Training Stage
#   start_training_step: 1

data_stages:
- data:
    dataset:
      dataloader_type: single
      dataset_max_tokens: null
      dataset_weights:
      - 0.5
      - 0.4
      - 0.1
      datasets:
      - filename_pattern: .*.ds
        folder: /fsx/loubna/tokenized_for_exps/fw_edu/fineweb-edu-full-cosmo2_merged
        skip_tokens: 0
      - filename_pattern: .*.ds
        # NOTE: lobuna deleted it
        # folder: /fsx/loubna/tokenized_for_exps/fw_edu/dclm-3T-cosmo2_merged
        folder: /fsx/phuc/datasets/100b_smol_ds/fw_edu_dclm_subset
        skip_tokens: 0
      - filename_pattern: .*.ds
        folder: /fsx/loubna/tokenized_for_exps/fw_edu/starcoderdata-full-cosmo_merged
        skip_tokens: 0
      pad_samples_to_global_batch_size: false
      skip_in_stream: true
    num_loading_workers: 0
    seed: 42
  name: Stable Training Stage
  start_training_step: 1

general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: fp8_for_nanotron
  run: exp701aab10_100m_bfloat16_baseline_like_exp602ae3_with_adam_eps_1.0e-8_and_bs_320_and_smol_dataset_but_wd_0.8
  seed: 42
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
  monitor_fwd_states: true
  monitor_optim_states: true
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    # std: 0.25 # sqrt(1/16)
    # std: 0.125 # sqrt(1/64)
    std: 0.04419417382415922 # sqrt(1/512)
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    # hidden_act: silu
    hidden_act: gelu
    hidden_size: 512
    initializer_range: 0.02
    intermediate_size: 2048
    is_llama_config: true
    max_position_embeddings: 64
    num_attention_heads: 16
    num_hidden_layers: 14
    num_key_value_heads: 16
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    tie_word_embeddings: false
    use_cache: true
    vocab_size: 49152

optimizer:
  accumulate_grad_in_fp32: false
  learning_rate_scheduler:
    learning_rate: 0.0006
    lr_decay_starting_step: null
    lr_decay_steps: null
    lr_decay_style: cosine
    lr_warmup_steps: 5000 # 10% warm up of total training steps
    lr_warmup_style: linear
    min_decay_lr: 0.00006

  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: custom_adamW
    torch_adam_is_fused: true
  weight_decay: 0.8
  zero_stage: 0
  # update_clipping: true

parallelism:
  dp: 1
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp: 1
  tp_linear_async_communication: false
  tp_mode: ALL_REDUCE

profiler: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: lvwerra/the-tokenizer-v1
  tokenizer_revision: null
tokens:
  # NOTE: micro_batch_size * sequence_length * batch_accumulation_per_replica
  # = 128 * 256 * 1 = 16384
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 320 # 256
  # micro_batch_size: 1
  sequence_length: 64
  train_steps: 24376
  val_check_interval: -1

s3_upload:
  remove_after_upload: true
  s5cmd_concurrency: 5
  s5cmd_numworkers: 16
  s5cmd_path: /fsx/nouamane/miniconda/envs/2-1-cu121/bin/s5cmd
  upload_s3_path: s3://phuc-experiments/fp8_for_nanotron/exp701aab10_100m_bfloat16_baseline_like_exp602ae3_with_adam_eps_1.0e-8_and_bs_320_and_smol_dataset_but_wd_0.8

experiment_logger:
  # id: exp701aab0_100m_bfloat16_baseline_like_exp602ae3_with_adam_eps_1.0e-8_and_bs_320_and_smol_dataset_but_wd_0.1
  tensorboard_logger:
    flush_secs: 30
    tensorboard_dir: /fsx/phuc/new_workspace/experiments/fp8_for_nanotron/exp701aab10_100m_bfloat16_baseline_like_exp602ae3_with_adam_eps_1.0e-8_and_bs_320_and_smol_dataset_but_wd_0.8/logs/tb_logs
  wandb_logger:
    wandb_entity: neuralink
    wandb_project: fp8_for_nanotron
