checkpoints:
  checkpoint_interval: 1000
  checkpoints_path: /fsx/nouamane/checkpoints
  checkpoints_path_is_shared_file_system: false
  load_lr_scheduler: true
  load_optimizer: true
  resume_checkpoint_path: null
  save_final_state: false
  save_initial_state: false
# data_stages:
# - data:
#     dataset:
#       dataset_folder:
#       - /fsx/loubna/datasets/llama_tokenized/fineweb-edu/merged
#       dataset_max_tokens: null
#       dataset_read_path: null
#       dataset_weights: null
#       pad_samples_to_global_batch_size: false
#       return_positions: true
#       shuffle_files: false
#       skip_in_stream: false
#       token_size_in_bytes: 4
#       tokenizer_name: meta-llama/Llama-3.2-1B
#       use_old_brrr_dataloader: false
#       vocab_size: 128256
#     num_loading_workers: 1
#     seed: 11
#   name: Stable Training Stage
#   start_training_step: 1


data_stages:
- data: 
    # dataset:
    #   dataset_folder:
    #   - /fsx/loubna/datasets/llama_tokenized/fineweb-edu/merged
    #   dataset_max_tokens: null
    #   dataset_read_path: null
    #   dataset_weights: null
    #   pad_samples_to_global_batch_size: false
    #   return_positions: true
    #   shuffle_files: false
    #   skip_in_stream: false
    #   token_size_in_bytes: 4
    #   tokenizer_name: meta-llama/Llama-3.2-1B
    #   use_old_brrr_dataloader: false
    #   vocab_size: 50304
    num_loading_workers: 1
    seed: 6198
  name: Stable Training Stage
  start_training_step: 1

general:
  # benchmark_csv_path: /fsx/phuc/new_workspace/snippets/experiment_configs/qwen_moe/exp19/benchmark_results.csv
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: qwen_moe
  run: exp20ba1_2_nodes_3A30B_llama3_hidden_size_and_num_experts_128_and_topk8_te_and_seq_len_4096_and_batch_accum512_and_mbs1_and_gbs1024_with_4m_and_elie_training_config_and_fineweb_but_dp2_tp8_ep8_edp4_and_lr0.000020_and_groupedgemm_and_allgather
  seed: 11
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
metrics_logging: null
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    scaling_method: NONE
    std: 0.02
  make_vocab_size_divisible_by: 1
  model_config:
    _attn_implementation: flash_attention_2
    _fused_rms_norm: true
    _fused_rotary_emb: true
    _use_doc_masking: true
    _use_qkv_packed: true
    attention_bias: false
    bos_token_id: 1
    eos_token_id: 0
    flex_attention_mask: null
    hidden_act: silu
    hidden_size: 8192
    initializer_range: 0.02
    intermediate_size: 28672
    is_qwen2_config: true
    max_position_embeddings: 4096
    moe_config:
      bias_activation_fusion: false
      disable_parameter_transpose_cache: false
      enable_shared_expert: false
      gradient_accumulation_fusion: false
      grouped_gemm_imple: megablock_grouped_gemm
      input_jitter_eps: null
      # layers:
      # - 0
      # - 1
      # - 2
      # - 3
      # - 4
      # - 5
      # - 6
      # - 7
      # - 8
      # - 9
      # - 10
      max_position_embeddings: null
      moe_expert_capacity_factor: null
      moe_hidden_size: 8192
      moe_impl: transformer_engine
      moe_intermediate_size: 768
      moe_pad_expert_input_to_capacity: false
      moe_router_dtype: null
      moe_router_expert_bias: null
      moe_router_group_topk: null
      moe_router_num_groups: null
      moe_router_pre_softmax: false
      moe_router_score_function: softmax
      moe_router_topk_scaling_factor: null
      moe_token_drop_policy: probs
      moe_z_loss_coeff: null
      num_experts: 128
      num_shared_experts: null
      permute_fusion: true
      rotary_base: null
      rotary_scaling_factor: null
      router_aux_loss_coef: 0.01
      router_load_balancing_type: aux_loss
      shared_expert_hidden_size: 8192
      shared_expert_intermediate_size: 768
      token_dispatcher_type: allgather
      # top_k: 12
      top_k: 8
      use_torch_permute: true
    no_rope_layer: null
    num_attention_heads: 32
    num_hidden_layers: 12
    num_key_value_heads: 8
    pad_token_id: 1
    pretraining_tp: 1
    rms_norm_eps: 1.0e-06
    rope_interleaved: false
    rope_scaling: null
    rope_theta: 10000.0
    sliding_window_size: null
    tie_word_embeddings: false
    use_cache: true
    # vocab_size: 128256
    vocab_size: 50304
    z_loss_coefficient: 0.001
    z_loss_enabled: true
optimizer:
  accumulate_grad_in_fp32: false
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0000000000001
    lr_decay_starting_step: 2560000
    lr_decay_steps: 640000
    lr_decay_style: linear
    lr_warmup_steps: 2000
    lr_warmup_style: linear
    min_decay_lr: 0
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.1
  weight_decay_exclude_named_params: []
  zero_stage: 0
parallelism:
  context_parallel_size: 1
  dp: 2
  enabled_moe: true
  expert_data_parallel_size: 2
  expert_parallel_size: 8
  expert_tensor_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  recompute_layer: false
  tp: 8
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
  tp_recompute_allgather: true
profiler: null
s3_upload: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: meta-llama/Llama-3.2-1B
  tokenizer_revision: null
tokens:
  # gbs = dp * mbs * accum * seq_len = 4 * 1 * 256 * 4096 = 4m
  batch_accumulation_per_replica: 512
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 1
  sequence_length: 4096
  train_steps: 100
  val_check_interval: -1
